name: simple_messenger
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  dio: ^5.5.0
  flutter_bloc: ^8.1.6
  firebase_core: ^3.1.1
  cupertino_icons: ^1.0.6
  surf_lint_rules: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3

flutter:
  uses-material-design: true
