name: simple_messenger
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  dio: ^5.5.0
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  flutter_bloc: ^8.1.6
  firebase_storage: ^12.1.0
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.6
  surf_lint_rules: ^3.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3

flutter:
  uses-material-design: true
